name: "CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      docker-tag: ${{ steps.docker-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'push' }}
            type=sha,format=long,enable=${{ github.event_name != 'push' }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Saving Docker image tag to outputs
        id: docker-tag
        run: echo "tag=${{ steps.meta.outputs.tags }}" >> $GITHUB_OUTPUT

  tests:
    runs-on: ubuntu-latest
    needs: build
    services:
      redis:
        image: redis:7.0.6
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: ${{ needs.build.outputs.docker-tag }}
      env:
        DISCORD_BOT_TOKEN: "test_token"
        REDIS_DSN: "redis://redis:6379"
        REDIS_ROTATION_LIFETIME: 86400

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: pytest

  cleanup-package-versions:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Delete all pre-release versions except y latest pre-release package versions
        uses: smartsquaregmbh/delete-old-packages@v0.6.0
        with:
          type: container
          user: ${{ github.repository_owner }}
          names: ${{ github.event.repository.name }}
          version-pattern: "sha-.*"
          keep: ${{ github.event_name != 'push' && 3 || 0 }}
          token: ${{ secrets.GH_PAT }}
